package an.maguste.android.navier.storage

import an.maguste.android.navier.data.Actor
import an.maguste.android.navier.data.Movie
import an.maguste.android.navier.storage.entitys.ActorEntity
import an.maguste.android.navier.storage.entitys.MovieEntity
import androidx.room.ColumnInfo
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext


interface MoviesRepository {
    /* movies */
    suspend fun getAllMovies(): List<Movie>
    suspend fun writeMovieIntoDB(movie: Movie)
    suspend fun rewriteMoviesListIntoDB(movies: List<Movie>)

    /* actors */
    suspend fun getAllActorsByMovie(movieId: Int): List<Actor>
    suspend fun rewriteActorsByMovieIntoDB(actors: List<Actor>, movieId: Int)
}

class MoviesRepositoryImpl : MoviesRepository {
    private val moviesDB = MoviesDatabase.instance

    override suspend fun writeMovieIntoDB(movie: Movie) = withContext(Dispatchers.IO) {
        moviesDB.moviesDao().insert(toMovieEntity(movie))
    }

    override suspend fun rewriteMoviesListIntoDB(movies: List<Movie>) = withContext(Dispatchers.IO){
        moviesDB.moviesDao().deleteAll()
        moviesDB.moviesDao().insertAll(movies.map { toMovieEntity(it) })
    }

    override suspend fun getAllMovies(): List<Movie> = withContext(Dispatchers.IO) {
        moviesDB.moviesDao().getAll().map { toMovieDomain(it) }
    }

    override suspend fun getAllActorsByMovie(movieId: Int): List<Actor> = withContext(Dispatchers.IO) {
        moviesDB.actorsDao().getAllByMovieId(movieId).map { toActorDomain(it) }
    }

    override suspend fun rewriteActorsByMovieIntoDB(actors: List<Actor>, movieId: Int) = withContext(Dispatchers.IO){
        moviesDB.actorsDao().deleteByMovieId(movieId)
        moviesDB.actorsDao().insertAll(actors.map { toActorEntity(it, movieId) })
    }

    private fun toActorDomain(actorEntity: ActorEntity) = Actor(
        id = actorEntity.actorId,
        name = actorEntity.name,
        picture = actorEntity.image
    )

    private fun toActorEntity(actorDomain: Actor, movieId: Int) = ActorEntity(
        id = null,  // autogenerated primary key
        actorId = actorDomain.id,
        name = actorDomain.name,
        image = actorDomain.picture,
        movie = movieId.toLong()
    )

    private fun toMovieEntity(movieDomain: Movie) = MovieEntity(
        id = movieDomain.id.toLong(),
        title = movieDomain.title,
        overview = movieDomain.overview,
        poster = movieDomain.poster,
        backdrop = movieDomain.backdrop,
        ratings = movieDomain.ratings,
        adult = movieDomain.adult,
        runtime = movieDomain.runtime,
        reviews = movieDomain.reviews,
        genres = movieDomain.genres.joinToString(","),
        like = movieDomain.like
    )

    private fun toMovieDomain(movieEntity: MovieEntity) = Movie(
        id = movieEntity.id.toInt(),
        title = movieEntity.title,
        overview = movieEntity.overview,
        poster = movieEntity.poster,
        backdrop = movieEntity.backdrop,
        ratings = movieEntity.ratings,
        adult = movieEntity.adult,
        runtime = movieEntity.runtime,
        reviews = movieEntity.reviews,
        genres = movieEntity.genres.split(",").map { it.trim() },
        like = movieEntity.like
    )
}