package an.maguste.android.navier.storage.mappers

import an.maguste.android.navier.data.Actor
import an.maguste.android.navier.storage.entitys.ActorEntity

object ActorMapper {

    internal fun toActorDomain(actorEntity: ActorEntity) = Actor(
        id = actorEntity.actorId,
        name = actorEntity.name,
        picture = actorEntity.image
    )

    internal fun toActorEntity(actorDomain: Actor, movieId: Int) = ActorEntity(
        id = null,  // autogenerated primary key
        actorId = actorDomain.id,
        name = actorDomain.name,
        image = actorDomain.picture,
        movie = movieId.toLong()
    )
}